### ISSUE TITLE
linkedin.com cannot be blocked

### ISSUE THREAD

**Issue by nermekov** [sdasda7777/ScheduleBlock#1]
![image](https://user-images.githubusercontent.com/20183989/222056125-52e68c6a-652d-4553-8daa-077a54e5d47d.png)
all other sites are blocked except linkedin

**Comment by sdasda7777** [comment]
Hi, thank you for the report. I believe I know what the issue is - some sites (Twitter, for another example) don't allow custom script execution, but the deployed version still relies on it. It is fixed in the version downloadable from this repository, but I didn't deploy it yet, because I wanted to fix few other things, which didn't really pan out 😐

**Comment by sdasda7777** [comment]
I finally had time to resolve the big issue that was preventing me from deploying a new version. Should be out in a few days, just need to polish up few other things.

**Comment by sdasda7777** [comment]
@nermekov It's waiting for approval right now, should be available in a few hours, maybe tommorow.

**Comment by sdasda7777** [comment]
It seems to be live now, is it fixed for you?

**Comment by nermekov** [comment]
Yes Thank You!
